// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAdvertisementsFields {
  /** Advertisement Image */
  advertisementImage?: Asset | undefined;

  /** Name */
  advertisementDescription?: string | undefined;

  /** HTML Ads Code */
  adsCode?: string | undefined;

  /** Advertisment Type */
  advertismentType: "code" | "custom";

  /** Redirect To */
  redirectTo?: string | undefined;

  /** Advertisment Position */
  advertismentPosition:
    | "Home Page Center"
    | "Events Page Center"
    | "Live Menu Page Center"
    | "News Menu Page Center"
    | "TV Page Center";
}

export interface IAdvertisements extends Entry<IAdvertisementsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "advertisements";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAuthorsFields {
  /** Author Name */
  authorName: "Tobias Gerold";
}

export interface IAuthors extends Entry<IAuthorsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "authors";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IEventSeatsFields {
  /** Seat Name */
  seatName:
    | "Block Blau - Normalpreis"
    | "Block Gelb - Normalpreis"
    | "Block Hellgrün - Normalpreis"
    | "Block Lila - Normalpreis"
    | "Block Rosa - Normalpreis"
    | "Block Schwarz - Normalpreis"
    | "Sitzplätze 1. Reihe - Normalpreis"
    | "Sitzplätze 2. Reihe - Normalpreis"
    | "Sitzplätze 3. Reihe - Normalpreis";

  /** Seat Price */
  seatPrice: number;
}

export interface IEventSeats extends Entry<IEventSeatsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "eventSeats";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFreeLatestVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName?: string | undefined;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Event Type */
  matchType: (
    | "Armdrücken"
    | "BJJ"
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
    | "Pro Wrestling"
    | "Ringen"
    | "Show"
    | "Talk"
    | "Royal FC"
  )[];

  /** Event Date */
  eventDate?: string | undefined;

  /** price */
  price: number;

  /** Video/Stream URL */
  videoStreamUrl?: string | undefined;

  /** Recommended */
  recommended?: boolean | undefined;
}

export interface IFreeLatestVideos extends Entry<IFreeLatestVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "freeLatestVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IHomePageFields {}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "homePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILiveFields {
  /** fight image */
  fightImage?: Asset | undefined;

  /** title */
  title: string;

  /** match date */
  matchDate: string;

  /** ticket price */
  ticketPrice: number;

  /** Match Type */
  matchType:
    | "Am Beliebtesten"
    | "TV"
    | "Zuletzt Hinzugefügt"
    | "Top Heis"
    | "Boxen"
    | "MMA"
    | "Royal FC"
    | "Auch Beliebt"
    | "Pro Wrestling";
}

export interface ILive extends Entry<ILiveFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "live";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface INewsFields {
  /** title */
  title: string;

  /** date */
  date: string;

  /** sub title */
  subTitle?: string | undefined;

  /** Article Banner Image  */
  image: Asset;

  /** Card Image */
  cardImage: Asset;

  /** Short Description */
  shortDescription: string;

  /** author */
  author: IAuthors;

  /** article content */
  articleContent: Document;
}

export interface INews extends Entry<INewsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "news";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageveranstaltungenFields {
  /** Section Dates */
  sectionDates?: Record<string, any> | undefined;
}

export interface IPageveranstaltungen
  extends Entry<IPageveranstaltungenFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "pageveranstaltungen";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IQencodeTranscodedAssetFields {
  /** Title */
  title?: string | undefined;

  /** Transcoding Data */
  task_data?: Record<string, any> | undefined;

  /** Media */
  media?: Asset | undefined;
}

export interface IQencodeTranscodedAsset
  extends Entry<IQencodeTranscodedAssetFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "qencodeTranscodedAsset";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IRecommendedVideosFields {
  /** Preview Image */
  previewImage: Asset;

  /** Tag Background Color */
  tagColor?: string | undefined;

  /** Tag Name */
  tagName: string;

  /** Tag Text Color */
  tagTextColor?: string | undefined;

  /** Champion Name */
  championName: string;

  /** Title */
  title: string;

  /** Time And Type Of Competition */
  timeAndTypeOfCompetition: string;

  /** Match Type */
  matchType: (
    | "Boxen"
    | "Doku"
    | "Karate"
    | "Kickboxen"
    | "MMA"
    | "Muay Thai"
  )[];
}

export interface IRecommendedVideos extends Entry<IRecommendedVideosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "recommendedVideos";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISliderBannerFields {
  /** Background Image */
  backgroundImage: Asset;

  /** title */
  title: string;

  /** date */
  date: string;

  /** Show Address */
  showAddress: string;

  /** Ticket Price */
  ticketPrice: number;

  /** Live URL */
  liveUrl: string;
}

export interface ISliderBanner extends Entry<ISliderBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "sliderBanner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITicketsFields {
  /** Ticket Card Image */
  ticketCover: Asset;

  /** Event Title */
  eventTitle: string;

  /** Event Time */
  eventTime: string;

  /** Price */
  price: number;

  /** Entering Time */
  enteringTime: number;

  /** Beginning Time */
  beginningTime: string;

  /** Event Duration */
  eventDuration: number;

  /** location */
  location: { lat: number; lon: number };

  /** Fight Image */
  fightImage: Asset;

  /** Available Seats */
  availableSeats: IEventSeats[];
}

export interface ITickets extends Entry<ITicketsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tickets";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IUpComingFightsFields {
  /** Card Image */
  fightImage: Asset;

  /** title */
  title: string;

  /** match date */
  matchDate: string;

  /** ticket price */
  ticketPrice: number;

  /** Article Image */
  articleImage: Asset;

  /** description */
  description: string;

  /** Availability */
  availability: "WORLDWIDE" | "GERMANY";

  /** RE-LIVE Price */
  reLivePrice?: number | undefined;

  /** On Demand 48Hrs */
  onDemand48hrs?: "Free" | "Paid" | undefined;

  /** location */
  location: { lat: number; lon: number };

  /** Address Name */
  addressName: string;

  /** Banner Item */
  bannerItem?: boolean | undefined;
}

export interface IUpComingFights extends Entry<IUpComingFightsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "upComingFights";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "advertisements"
  | "authors"
  | "eventSeats"
  | "freeLatestVideos"
  | "homePage"
  | "live"
  | "news"
  | "pageveranstaltungen"
  | "qencodeTranscodedAsset"
  | "recommendedVideos"
  | "sliderBanner"
  | "tickets"
  | "upComingFights";

export type IEntry =
  | IAdvertisements
  | IAuthors
  | IEventSeats
  | IFreeLatestVideos
  | IHomePage
  | ILive
  | INews
  | IPageveranstaltungen
  | IQencodeTranscodedAsset
  | IRecommendedVideos
  | ISliderBanner
  | ITickets
  | IUpComingFights;

export type LOCALE_CODE = "de" | "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
