import React, { Suspense } from "react";
import { dir } from "i18next";
import localFont from "next/font/local";
import { SessionProvider } from "next-auth/react";

import Header from "./components/Header";
import Footer from "./components/Footer";

import AuthModal from "./components/AuthModal";

import { i18n } from "@i18n/settings";
import "@/theme/globals.css";
import { Provider } from "./store/provider";


export async function generateStaticParams() {
  return i18n.locales.map((lng) => ({ lng }));
}

const amisProFont = localFont({
  src: [
    {
      path: "./assets/fonts/amsi-pro/AmsiPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/amsi-pro/AmsiPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/amsi-pro/AmsiPro-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-amis-pro",
});

export const metadata = {
  title: "WahoopRedit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  console.log(lng);

  return (
    <html lang={lng} dir={dir(lng)}>
      <body >
        <Provider>
          <AuthModal />
          <Header lng={lng} />
          <Suspense>
            <main className="main">{children}</main>
          </Suspense>
          <Footer lng={lng} />
        </Provider>
      </body>
    </html>
  );
}
